config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/react', to: "pages#react", as: 'react'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def react
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Angie</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Angie DUHARD</h1>

<h3>Mes projets</h3>
<ul>
  <li>
    <a href="https://www.openairconnect.com">OpenAirConnect</a> (application web pensée pour mobiles)
    <%= link_to "Voir le Github", "https://github.com/AngieJW/OPENAIRCONNECT" %>
    </li>
  <li>
    Green Drive
  </li>
  <li>
    <%= link_to "Pages React recréées", react_path %></li>
</ul>

app/views/pages/react.html.erb
<h2>Pages recréées entièrement avec React </h2>
<h6>suite à des tutoriels sur Youtube</h6>
<ul>
  <li>
    Tesla
    <%= link_to "Voir la front page", "https://tesla.angieduhard.com" %>
    <%= link_to "Voir le Github", "https://github.com/AngieJW/tesla-clone"   %>
  </li>

  </li>
  <li>GPT3
    <%= link_to "Voir la front page", "https://gpt3.angieduhard.com" %>
    <%= link_to "Voir le Github", "https://github.com/AngieJW/gpt3"   %></li>
</ul>

app/views/shared/_footer.html.erb
© 2023 Designed & built by Angie Duhard